apiVersion: v1
kind: Service
metadata:
  name: Capstone-Cluster-app
spec:
  selector:
    app: Capstone-Cluster-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80