Description:
  Capstone project / Cheick GUITI @Udacity

Parameters:

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  
Mappings:
  DefaultConfig:
    VPC:
      CIDR: 10.0.0.0/16
    Subnet1:
      CIDR: 10.0.0.0/24
    Subnet2:
      CIDR: 10.0.1.0/24
    Subnet3:
      CIDR: 10.0.2.0/24


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !FindInMap
        - DefaultConfig
        - VPC
        - CIDR
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 0, !GetAZs '' ]
        CidrBlock: !FindInMap
          - DefaultConfig
          - Subnet1
          - CIDR
        Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName}-Subnet-1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !FindInMap
        - DefaultConfig
        - Subnet2
        - CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Subnet-2
  
  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs  '' ]
      CidrBlock: !FindInMap
        - DefaultConfig
        - Subnet3
        - CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Subnet-3

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2

  Subnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet3


Outputs:
  
  VPC: 
      Description: A reference to the created VPC
      Value: !Ref VPC
      Export:
        Name: !Sub ${EnvironmentName}-VPCID

  RouteTable:
      Description: Public Routing
      Value: !Ref RouteTable
      Export:
        Name: !Sub ${EnvironmentName}-ROUTETABLE

  Subnets:
      Description: Public subnets IDs
      Value: !Join [ ",", [ !Ref Subnet1, !Ref Subnet2, !Ref Subnet3 ]]
      Export:
        Name: !Sub ${EnvironmentName}-Subnets

  Subnet1:
      Value: !Ref Subnet1
      Export:
        Name: !Sub ${EnvironmentName}-Subnet-1

  Subnet2: 
      Value: !Ref Subnet2
      Export:
        Name: !Sub ${EnvironmentName}-Subnet-2

  Subnet3:
      Value: !Ref Subnet3
      Export:
        Name: !Sub ${EnvironmentName}-Subnet-3